title: Riding the Ridge
logo: # You can add own logo image.
description: #A blog experiment
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://www.ridingtheridge.com/" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name:
  bio:

# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
# email: # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Riding the Ridge # Add your hero title
hero-subtitle: A place to share some writing & dancing.
# A blog experiment.
# A place to share some thoughts (essays), feelings (poems), and sensations (dance).
# An experiment against polarisation.
# A blog to share little pieces of writing and dancing.
# hero-image: images/ridge8.jpeg
hero-image: images/ridge3.webp

# Footer
footer: false
footer-image: images/spongebob.gif # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: ridingtheridge # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 1000
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
